# Generated by Django 5.0.4 on 2024-04-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkProvisioning.site')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('genericdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='networkProvisioning.genericdevice')),
                ('loopback_ip', models.GenericIPAddressField()),
            ],
            bases=('networkProvisioning.genericdevice',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('genericdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='networkProvisioning.genericdevice')),
                ('mgmt_ip', models.GenericIPAddressField()),
            ],
            bases=('networkProvisioning.genericdevice',),
        ),
        migrations.AddField(
            model_name='genericdevice',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkProvisioning.serialnumber'),
        ),
    ]
