# Generated by Django 5.0.4 on 2024-04-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0002_genericdevice_serialnumber_router_switch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name_plural': 'Switches'},
        ),
    ]
