# Generated by Django 5.0.4 on 2024-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0003_alter_switch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='loopback_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='mgmt_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
