# Generated by Django 5.0.4 on 2024-04-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0004_alter_router_loopback_ip_alter_serialnumber_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdevice',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkProvisioning.serialnumber', unique=True),
        ),
    ]
