# Generated by Django 5.0.4 on 2024-04-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0006_alter_genericdevice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdevice',
            name='serial_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='networkProvisioning.serialnumber'),
        ),
    ]
