# Generated by Django 5.0.4 on 2024-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0007_alter_genericdevice_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericdevice',
            name='provisioning_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
