# Generated by Django 5.0.4 on 2024-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0010_rename_provisioned_status_genericdevice_provisioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericdevice',
            name='configuration_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
