# Generated by Django 5.0.4 on 2024-04-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0014_remove_link_side_a_remove_link_side_a_intf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='side_a',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='side_a', to='networkProvisioning.router'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(default=None, help_text='Automatically picked when saving', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='side_b',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='side_b', to='networkProvisioning.router'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(default=None, help_text='Automatically picked when saving', max_length=255),
            preserve_default=False,
        ),
    ]
