# Generated by Django 5.0.4 on 2024-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0015_link_side_a_link_side_a_intf_link_side_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(blank=True, help_text='Automatically picked when saving', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(blank=True, help_text='Automatically picked when saving', max_length=255, null=True),
        ),
    ]
