# Generated by Django 5.0.4 on 2024-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0016_alter_link_side_a_intf_alter_link_side_b_intf'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(default='Tull', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='subnet',
            field=models.GenericIPAddressField(default=None, help_text='Automatically fetched from IPAM when saving'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(blank=True, help_text='Automatically picked from model when saving if empty', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(blank=True, help_text='Automatically picked from model when saving if empty', max_length=255, null=True),
        ),
    ]
