# Generated by Django 5.0.4 on 2024-04-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0019_devicemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialnumber',
            name='part_number',
        ),
    ]
