# Generated by Django 5.0.4 on 2024-04-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0020_remove_serialnumber_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networkProvisioning.devicemodel'),
        ),
    ]
