# Generated by Django 5.0.4 on 2024-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0022_remove_devicemodel_num_of_gigabits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='interface_numbers',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
