# Generated by Django 5.0.4 on 2024-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0023_devicemodel_interface_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='name',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
    ]
