# Generated by Django 5.0.4 on 2024-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0024_devicemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='hardware_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
