# Generated by Django 5.0.4 on 2024-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0025_devicemodel_hardware_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('speed', models.CharField(choices=[('10', '10GE'), ('1', '1GE'), ('40', '40GE'), ('100', '100GE')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='supported_specs',
            field=models.ManyToManyField(to='networkProvisioning.interfacespec'),
        ),
    ]
