# Generated by Django 5.0.4 on 2024-04-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0026_interfacespec_interface_supported_specs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='InterfaceSpec',
        ),
    ]
