# Generated by Django 5.0.4 on 2024-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0028_router_available_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(blank=True, help_text='click Save and continue.. to see list of available interfaces', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(blank=True, help_text='click Save and continue.. to see list of available interfaces', max_length=255, null=True),
        ),
    ]
