# Generated by Django 5.0.4 on 2024-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0029_alter_link_side_a_intf_alter_link_side_b_intf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(blank=True, help_text='click Save and continue to see list of available interfaces', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(blank=True, help_text='click Save and continue to see list of available interfaces', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='subnet',
            field=models.GenericIPAddressField(blank=True, help_text='Automatically fetched from IPAM when saving', null=True),
        ),
    ]
