# Generated by Django 5.0.4 on 2024-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0032_genericdevice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='subnet',
            field=models.CharField(blank=True, help_text='Automatically fetched from IPAM when saving', max_length=255, null=True),
        ),
    ]
