# Generated by Django 5.0.4 on 2024-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0033_alter_link_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='interface_prefixes',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericdevice',
            name='configuration_url',
            field=models.URLField(blank=True, help_text='WIP: Should be available on a uuid URL when finished', null=True),
        ),
        migrations.AlterField(
            model_name='genericdevice',
            name='provisioned',
            field=models.BooleanField(blank=True, help_text='Automatically set based on ZTP status', null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='available_interfaces',
            field=models.JSONField(help_text='Automatically generated/updated when saving router or link'),
        ),
        migrations.AlterField(
            model_name='router',
            name='loopback_ip',
            field=models.GenericIPAddressField(help_text='Implicit /32', unique=True),
        ),
    ]
