# Generated by Django 5.0.4 on 2024-04-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0035_remove_devicemodel_interface_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interface_prefixes', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='networkProvisioning.operatingsystems'),
        ),
    ]
