# Generated by Django 5.0.4 on 2024-04-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0036_operatingsystems_devicemodel_operating_system'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatingSystems',
            new_name='OperatingSystem',
        ),
    ]
