# Generated by Django 5.0.4 on 2024-04-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0037_rename_operatingsystems_operatingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='side_a_prefix',
            field=models.CharField(blank=True, help_text='click Save and continue to see list of available choices', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='side_b_prefix',
            field=models.CharField(blank=True, help_text='click Save and continue to see list of available choices', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(blank=True, help_text='click Save and continue to see list of available choices', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(blank=True, help_text='click Save and continue to see list of available choices', max_length=255, null=True),
        ),
    ]
