# Generated by Django 5.0.4 on 2024-04-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0038_link_side_a_prefix_link_side_b_prefix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='description',
            new_name='circuit_id',
        ),
        migrations.AlterField(
            model_name='genericdevice',
            name='configuration_url',
            field=models.URLField(blank=True, help_text='WIP: Should be available on an UUID URL when finished', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_a_intf',
            field=models.CharField(blank=True, help_text='Choose sides and then click "Save and continue editing" to see list of available choices', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_a_prefix',
            field=models.CharField(blank=True, help_text='Choose sides and then click "Save and continue editing" to see list of available choices', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_intf',
            field=models.CharField(blank=True, help_text='Choose sides and then click "Save and continue editing" to see list of available choices', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='side_b_prefix',
            field=models.CharField(blank=True, help_text='Choose sides and then click "Save and continue editing" to see list of available choices', max_length=255, null=True),
        ),
    ]
