# Generated by Django 5.0.4 on 2024-04-22 18:22

import django.db.models.deletion
import networkProvisioning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkProvisioning', '0039_rename_description_link_circuit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdevice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networkProvisioning.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(storage=networkProvisioning.models.OverwriteStorage(), upload_to='networkProvisioning/template_files/'),
        ),
    ]
